services:
  frontend:
    image: asia-southeast3-docker.pkg.dev/supa-cloud-app/my-repo/my-docker-app-frontend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - DATABASE_URL=${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    image: asia-southeast3-docker.pkg.dev/supa-cloud-app/my-repo/my-docker-app-backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - DATABASE_URL=${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config:
